[package]
name = "rslisp-functions"
version = "0.1.0"
authors = ["Fisher Darling <fdarlingco@gmail.com>"]
edition = "2018"

[dependencies]
rslisp = { path = "../" }
env_logger = "*"
log = "*"
im = "12.3.4"
